name: Test Formula

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test formula syntax
      run: |
        # Modern brew audit syntax using formula name instead of file path
        brew tap jsonify/vox .
        brew audit --strict vox
        
    - name: Test formula installation (if release exists)
      run: |
        # Only test if the version exists in releases
        VERSION=$(grep 'version "' Formula/vox.rb | sed 's/.*version "\(.*\)".*/\1/')
        if gh release view "v$VERSION" --repo jsonify/vox &>/dev/null; then
          # Install from local tap
          brew install vox
          brew test vox || echo "Test command not available (this is normal for simple formulas)"
        else
          echo "Release v$VERSION not found, skipping installation test"
        fi
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
        GH_TOKEN: ${{ github.token }}
